### ISSUE TITLE
failure to pack

### ISSUE THREAD

**Issue by ioanagrozav** [shopgun/pack-animal#45]
using fleggaard may feed on mobile

"err": {
        "message": "greedyPack failure to pack, please open an issue at https://github.com/shopgun/pack-animal/issues and include this data:\neyJwb2x5Z29ucyI6W1t7IngiOjAsInkiOjB9LHsieCI6MTY5NywieSI6MH0seyJ4IjoxNjk3LCJ5IjoyMTB9LHsieCI6MCwieSI6MjEwfSx7IngiOjAsInkiOjB9XSxbeyJ4IjowLCJ5IjowfSx7IngiOjM1OTgsInkiOjB9LHsieCI6MzU5OCwieSI6MjMxOX0seyJ4IjowLCJ5IjoyMzE5fSx7IngiOjAsInkiOjB9XV0sInJlY3RhbmdsZUhlaWdodCI6MTI4LCJyZWN0YW5nbGVXaWR0aCI6MTY0fQ==",
        "meta": {
            "polygons": [
                [
                    {
                        "x": 0,
                        "y": 0
                    },
                    {
                        "x": 1697,
                        "y": 0
                    },
                    {
                        "x": 1697,
                        "y": 210
                    },
                    {
                        "x": 0,
                        "y": 210
                    },
                    {
                        "x": 0,
                        "y": 0
                    }
                ],
                [
                    {
                        "x": 0,
                        "y": 0
                    },
                    {
                        "x": 3598,
                        "y": 0
                    },
                    {
                        "x": 3598,
                        "y": 2319
                    },
                    {
                        "x": 0,
                        "y": 2319
                    },
                    {
                        "x": 0,
                        "y": 0
                    }
                ]
            ],
            "rectangleHeight": 128,
            "rectangleWidth": 164,
            "scale": 0
        }
    },
    "stack": "Error: greedyPack failure to pack, please open an issue at https://github.com/shopgun/pack-animal/issues and include this data:\neyJwb2x5Z29ucyI6W1t7IngiOjAsInkiOjB9LHsieCI6MTY5NywieSI6MH0seyJ4IjoxNjk3LCJ5IjoyMTB9LHsieCI6MCwieSI6MjEwfSx7IngiOjAsInkiOjB9XSxbeyJ4IjowLCJ5IjowfSx7IngiOjM1OTgsInkiOjB9LHsieCI6MzU5OCwieSI6MjMxOX0seyJ4IjowLCJ5IjoyMzE5fSx7IngiOjAsInkiOjB9XV0sInJlY3RhbmdsZUhlaWdodCI6MTI4LCJyZWN0YW5nbGVXaWR0aCI6MTY0fQ==\n    at greedyPack (/Users/ioana/bumblebee/node_modules/pack-animal/dist/pack-animal.umd.js:1260:19)\n    at packAnimal (/Users/ioana/bumblebee/node_modules/pack-animal/dist/pack-animal.umd.js:1870:29)\n    at renderImageViews (/Users/ioana/bumblebee/publication_core/offer/templates/images.js:78:29)\n    at Object.module.exports [as images] (/Users/ioana/bumblebee/publication_core/offer/templates/images.js:23:22)\n    at Object.render (/Users/ioana/bumblebee/publication_modules/fleggaard/templates/offer_cell/index.js:238:45)\n    at blocks.forEach (/Users/ioana/bumblebee/publication_modules/fleggaard/templates/offer_cell/index.js:359:19)\n    at Map.forEach (<anonymous>)\n    at module.exports (/Users/ioana/bumblebee/publication_modules/fleggaard/templates/offer_cell/index.js:357:12)\n    at child_views.grid.cells.map (/Users/ioana/bumblebee/publication_modules/fleggaard/templates/offers-grid.js:31:20)\n    at Array.map (<anonymous>)\n    at module.exports (/Users/ioana/bumblebee/publication_modules/fleggaard/templates/offers-grid.js:30:33)\n    at Object.renderSection (/Users/ioana/bumblebee/publication_core/incito-builder.js:268:46)\n    at Object.build (/Users/ioana/bumblebee/publication_core/incito-builder.js:74:59)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:229:7)",
    "level": "error"
}

**Comment by martensievers** [comment]
We continue to have this error in the Fleggaard Incito.

Error: greedyPack failure to pack, please open an issue at https://github.com/shopgun/pack-animal/issues and include this data:
eyJwb2x5Z29ucyI6W1t7IngiOjAsInkiOjB9LHsieCI6MTYwOSwieSI6MH0seyJ4IjoxNjA5LCJ5IjoyNjB9LHsieCI6MCwieSI6MjYwfSx7IngiOjAsInkiOjB9XSxbeyJ4IjowLCJ5IjowfSx7IngiOjE4OTIsInkiOjB9LHsieCI6MTg5MiwieSI6Mjc5M30seyJ4IjowLCJ5IjoyNzkzfSx7IngiOjAsInkiOjB9XV0sInJlY3RhbmdsZUhlaWdodCI6OTEsInJlY3RhbmdsZVdpZHRoIjoxNDR9
    at greedyPack (/opt/bumblebee/node_modules/pack-animal/dist/pack-animal.umd.js:1260:19)
    at packAnimal (/opt/bumblebee/node_modules/pack-animal/dist/pack-animal.umd.js:1870:29)
    at renderImageViews (/opt/bumblebee/publication_core/offer/templates/images.js:76:29)
    at Object.module.exports [as images] (/opt/bumblebee/publication_core/offer/templates/images.js:21:22)
    at Object.render (/opt/bumblebee/publication_modules/fleggaard/templates/offer_cell/index.js:257:45)
    at blocks.forEach (/opt/bumblebee/publication_modules/fleggaard/templates/offer_cell/index.js:377:19)
    at Map.forEach (<anonymous>)
    at module.exports (/opt/bumblebee/publication_modules/fleggaard/templates/offer_cell/index.js:375:12)
    at child_views.grid.cells.map (/opt/bumblebee/publication_modules/fleggaard/templates/offers-grid.js:31:20)
    at Array.map (<anonymous>)
    at module.exports (/opt/bumblebee/publication_modules/fleggaard/templates/offers-grid.js:30:33)
    at Object.renderSection (/opt/bumblebee/publication_core/incito-builder.js:277:46)
    at Object.build (/opt/bumblebee/publication_core/incito-builder.js:79:59)
    at <anonymous>
